### PR TITLE
Update translation, Fix the issue with subtitles in cutscenes failing to load translated text

### PR DESCRIPTION
**Pull request by lishaoxia1985**
Please add my heroesChronicles to vcmi-mods:
https://github.com/lishaoxia1985/heroesChronicles

### CODE REVIEW

**Comment by Laserlicht** [comment]
@misiokles Also merge?

@lishaoxia1985 We should not add the chronicles to our repository. Because it is still available to buy on gog: https://www.gog.com/de/game/heroes_chronicles_all_chapters
We need to support these gog files in VCMI itself: https://github.com/vcmi/vcmi/issues/2258

**Comment by misiokles** [comment]
@Laserlicht how to unfork sth from vcmi-mods? I already forked heroesChronicles :(

**Comment by Laserlicht** [comment]
@misiokles Just delete this repo. Not sure if you have the permission. If not we need to ask admin of organisation.

**Comment by misiokles** [comment]
@lishaoxia1985 I added your mod to vcmi-1.4-archive list, so it is now available in launcher

**Pull request merged**
